services:

  inductive:
    image: inductiveautomation/ignition:8.1
    container_name: ignition
    hostname: ignition
    ports:
      - 9088:8088
      - 62541:62541
    environment:
      - IGNITION_EDITION=edge
      - ACCEPT_IGNITION_EULA=Y
      - TZ=US
      - GATEWAY_ADMIN_USERNAME=admin
      - GATEWAY_ADMIN_PASSWORD=admin
    command: >
      -n docker-test
      -a 0.0.0.0
      -h 9088
      -s 9043

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=TestOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=TestBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    # volumes:
    #   - influxdb-data:/var/lib/influxdb2

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - inductive

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
    # volumes:
    #   - grafana-data:/var/lib/grafana


# volumes:
#   influxdb-data:
#   grafana-data:
