services:
  collector:
    build: ./collector
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=TestOrg
      - INFLUXDB_BUCKET=TestBucket

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=TestOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=TestBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    # volumes:
    #   - influxdb-data:/var/lib/influxdb2

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
    # volumes:
    #   - grafana-data:/var/lib/grafana

# volumes:
#   influxdb-data:
#   grafana-data: