services:

  ignition:
    image: inductiveautomation/ignition:8.1
    container_name: ignition
    hostname: ignition
    ports:
      - 9088:8088
      - 62541:62541
    environment:
      - IGNITION_EDITION=edge
      - ACCEPT_IGNITION_EULA=Y
      - TZ=US
      - GATEWAY_ADMIN_USERNAME=admin
      - GATEWAY_ADMIN_PASSWORD=admin
    command: >
      -n docker-test
      -a 0.0.0.0
      -h 9088
      -s 9043

  timescaledb:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: timescaledb
    hostname: timescaledb
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - PGTZ=America/New_York
      - POSTGRES_USER=${TIMESCALEDB_USER}
      - POSTGRES_PASSWORD=${TIMESCALEDB_PASS}
      - PGUSER=${TIMESCALEDB_USER}
      - PGPASSWORD=${TIMESCALEDB_PASS}
      - PGDATABASE=metrics


  telegraf:
    image: telegraf:1.32.0
    container_name: telegraf
    hostname: telegraf
    env_file:
      - ./.env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - timescaledb
      - ignition

  grafana:
    image: grafana/grafana:11.2.0-ubuntu
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - telegraf
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning
    #   - grafana-data:/var/lib/grafana


# volumes:
#   influxdb-data:
#   grafana-data:
